services:
    dmzx.noaccess.listener:
        class: dmzx\noaccess\event\listener
        arguments:
            - '@config'
            - '@user'
            - '@auth'
        tags:
            - { name: event.listener }
